version: "3.8"

services:
  jupyter:
    build:
      context: ./jupyter
      dockerfile: ../Dockerfile
    ports:
      - 8888:8888
    volumes:
      - type: bind
        source: ./jupyter/notebooks
        target: /home/jovyan/notebooks
      - type: bind
        source: ./jupyter/data
        target: /home/jovyan/data
      - type: bind
        source: ./jupyter/src
        target: /home/jovyan/src
    env_file: .env
    environment:
      - JUPYTER_ENABLE_LAB=yes
